[package]
name = "triangle-from-scratch"
version = "0.1.0"
edition = "2021"

[dependencies]
c-types = { path = "crates/c-types", package = "triangle-from-scratch-c-types" }

[profile.release]
lto = "thin"

[workspace]
members = [
    "crates/*"
]
